### PR TITLE
adsfasdf

### PR DESCRIPTION
**Pull request by calvinyoung14**
adsfasdf

### CODE REVIEW

**Review by Ishjot — CHANGES_REQUESTED** [review]
You have to do a few things before we merge this to master

1. Change the name of the class to Player instead of player.
2. Revert all the changes you made to master 
3. Be more descriptive in the name of your Pull Request so it's easier for us all to understand.

**Comment by calvinyoung14** [comment]
what do you mean revert all changes to master? you mean that one time i accidentally pushed without using a pull request? if thats what you mean i dont have the original master anymore

**Comment by Ishjot** [comment]
Yes, that's what I mean. And yes you do have the original master. You should Google "how to revert changes using git." Git keeps a changelog of every change you have ever made, so it's possible to revert back to a past state and push that up to master.

**Comment by Ishjot** [comment]
It's fine, I did it. But please still make your pull request name more descriptive.

**Pull request closed without merging**
